# Generated by Django 3.1.6 on 2021-02-21 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0002_auto_20210221_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderdetails',
            new_name='Orderdetail',
        ),
    ]
