# Generated by Django 3.1.6 on 2021-02-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_auto_20210221_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
    ]
