# Generated by Django 3.1.6 on 2021-02-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default='add'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Native',
            field=models.CharField(default='addd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='soilType',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
    ]
