# Generated by Django 3.1.6 on 2021-02-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_auto_20210223_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
    ]
