# Generated by Django 3.1.7 on 2021-02-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_auto_20210223_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
