# Generated by Django 3.1.7 on 2021-02-24 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=datetime.datetime(2021, 2, 24, 19, 56, 5, 300316, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
